# https://docs.travis-ci.com/user/languages/r
language: r
r_packages: 
  - yaml
  - pander
  - stringr
  - data.table
  - parallel
bioc_packages: ShortRead
r:
  - release
cache: packages
install:
  - R -e "devtools::install_deps(dep = T)"
script:
  - git clone https://github.com/cnobles/seqFiltR.git
  - cd seqFiltR
  - bash tests/test.sh
